spring:
    datasource:
        url: jdbc:postgresql://localhost:5434/library
        password: postgres
        username: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
      database: postgresql
      hibernate.ddl-auto: validate
      open-in-view: false
    liquibase.change-log: classpath:/db/changelog/changelog-master.xml
    cloud.openfeign.client.config:
        books:
          url: ${BOOKS_FEIGN_URL}
          connect-timeout: 6000
        clients:
          url: ${CLIENTS_FEIGN_URL}
          connect-timeout: 6000
greeting: libriry service3
